name: "vocoder"
backend: "python"
max_batch_size: ${triton_max_batch_size}
dynamic_batching {
    max_queue_delay_microseconds: ${max_queue_delay_microseconds}
}
parameters [
  {
   key: "model_dir",
   value: {string_value:"${model_dir}"}
  }
]

input [
  {
    name: "mel"
    data_type: TYPE_FP32
    dims: [80, -1]
  },
  {
    name: "finalize"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    reshape: { shape: [ ] }
  }
]
output [
  {
    name: "tts_speech"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]