// This file is @generated by prost-build.
/// Main inference request with different modes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceRequest {
    /// Text to synthesize
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Optional parameters
    ///
    /// Speech speed multiplier (default: 1.0)
    #[prost(float, tag = "6")]
    pub speed: f32,
    /// Enable streaming output (default: true)
    #[prost(bool, tag = "7")]
    pub stream: bool,
    /// Enable text normalization (default: true)
    #[prost(bool, tag = "8")]
    pub text_frontend: bool,
    /// Inference mode
    #[prost(oneof = "inference_request::Mode", tags = "2, 3, 4, 5")]
    pub mode: ::core::option::Option<inference_request::Mode>,
}
/// Nested message and enum types in `InferenceRequest`.
pub mod inference_request {
    /// Inference mode
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Mode {
        #[prost(message, tag = "2")]
        Sft(super::SftMode),
        #[prost(message, tag = "3")]
        ZeroShot(super::ZeroShotMode),
        #[prost(message, tag = "4")]
        CrossLingual(super::CrossLingualMode),
        #[prost(message, tag = "5")]
        Instruct(super::InstructMode),
    }
}
/// SFT (Speaker Fine-Tuned) mode - use pre-trained speaker
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SftMode {
    /// e.g., "中文女", "中文男"
    #[prost(string, tag = "1")]
    pub speaker_id: ::prost::alloc::string::String,
}
/// Zero-shot voice cloning mode
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZeroShotMode {
    /// Text that matches the prompt audio
    #[prost(string, tag = "1")]
    pub prompt_text: ::prost::alloc::string::String,
    /// 16-bit PCM audio at 16kHz
    #[prost(bytes = "vec", tag = "2")]
    pub prompt_audio: ::prost::alloc::vec::Vec<u8>,
}
/// Cross-lingual mode - clone voice to different language
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrossLingualMode {
    /// 16-bit PCM audio at 16kHz
    #[prost(bytes = "vec", tag = "1")]
    pub prompt_audio: ::prost::alloc::vec::Vec<u8>,
}
/// Instruct mode - with style/emotion instructions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstructMode {
    /// Base speaker
    #[prost(string, tag = "1")]
    pub speaker_id: ::prost::alloc::string::String,
    /// Instruction for style/emotion
    #[prost(string, tag = "2")]
    pub instruct_text: ::prost::alloc::string::String,
}
/// Streaming audio chunk
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioChunk {
    /// 16-bit PCM audio at 22050Hz
    #[prost(bytes = "vec", tag = "1")]
    pub audio_data: ::prost::alloc::vec::Vec<u8>,
    /// Chunk sequence number
    #[prost(uint32, tag = "2")]
    pub chunk_index: u32,
    /// True if this is the last chunk
    #[prost(bool, tag = "3")]
    pub is_final: bool,
    /// Metadata (only in first chunk)
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<AudioMetadata>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AudioMetadata {
    /// Always 22050
    #[prost(uint32, tag = "1")]
    pub sample_rate: u32,
    /// Always 1 (mono)
    #[prost(uint32, tag = "2")]
    pub channels: u32,
    /// Always 16
    #[prost(uint32, tag = "3")]
    pub bits_per_sample: u32,
}
/// List speakers request/response
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListSpeakersRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSpeakersResponse {
    #[prost(string, repeated, tag = "1")]
    pub speakers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Health check
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub gpu_available: bool,
    #[prost(string, tag = "4")]
    pub gpu_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub gpu_memory_mb: u64,
}
/// Generated client implementations.
pub mod cosy_voice_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// CosyVoice TTS Service
    #[derive(Debug, Clone)]
    pub struct CosyVoiceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CosyVoiceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CosyVoiceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CosyVoiceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CosyVoiceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Main inference endpoint - streams audio chunks back
        pub async fn inference(
            &mut self,
            request: impl tonic::IntoRequest<super::InferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AudioChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosyvoice.CosyVoiceService/Inference",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosyvoice.CosyVoiceService", "Inference"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// List available speaker IDs for SFT mode
        pub async fn list_speakers(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSpeakersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSpeakersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosyvoice.CosyVoiceService/ListSpeakers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosyvoice.CosyVoiceService", "ListSpeakers"));
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosyvoice.CosyVoiceService/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosyvoice.CosyVoiceService", "HealthCheck"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod cosy_voice_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CosyVoiceServiceServer.
    #[async_trait]
    pub trait CosyVoiceService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Inference method.
        type InferenceStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AudioChunk, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Main inference endpoint - streams audio chunks back
        async fn inference(
            &self,
            request: tonic::Request<super::InferenceRequest>,
        ) -> std::result::Result<tonic::Response<Self::InferenceStream>, tonic::Status>;
        /// List available speaker IDs for SFT mode
        async fn list_speakers(
            &self,
            request: tonic::Request<super::ListSpeakersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSpeakersResponse>,
            tonic::Status,
        >;
        /// Health check
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
    }
    /// CosyVoice TTS Service
    #[derive(Debug)]
    pub struct CosyVoiceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CosyVoiceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CosyVoiceServiceServer<T>
    where
        T: CosyVoiceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cosyvoice.CosyVoiceService/Inference" => {
                    #[allow(non_camel_case_types)]
                    struct InferenceSvc<T: CosyVoiceService>(pub Arc<T>);
                    impl<
                        T: CosyVoiceService,
                    > tonic::server::ServerStreamingService<super::InferenceRequest>
                    for InferenceSvc<T> {
                        type Response = super::AudioChunk;
                        type ResponseStream = T::InferenceStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InferenceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CosyVoiceService>::inference(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InferenceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cosyvoice.CosyVoiceService/ListSpeakers" => {
                    #[allow(non_camel_case_types)]
                    struct ListSpeakersSvc<T: CosyVoiceService>(pub Arc<T>);
                    impl<
                        T: CosyVoiceService,
                    > tonic::server::UnaryService<super::ListSpeakersRequest>
                    for ListSpeakersSvc<T> {
                        type Response = super::ListSpeakersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListSpeakersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CosyVoiceService>::list_speakers(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSpeakersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cosyvoice.CosyVoiceService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: CosyVoiceService>(pub Arc<T>);
                    impl<
                        T: CosyVoiceService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CosyVoiceService>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CosyVoiceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cosyvoice.CosyVoiceService";
    impl<T> tonic::server::NamedService for CosyVoiceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
